parameters:
    database_driver: pdo_oci
    database_host: 127.0.0.1
    database_port: '1521'
    database_name: XE
    database_user: admin
    database_password: admin
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: 28e7e93d65428908c511f5e97f70d47fb65616af
    database_path: null
