generateRemboursement:
    pattern:  /Générer-Remboursement.html
    defaults: { _controller: "EmpruntBundle:Remboursement:generateRemboursement" }
  
consulterRemboursementParTirage:
    pattern:  /Consulter-Remboursement-Par-Tirage.html
    defaults: { _controller: "EmpruntBundle:Remboursement:consulterRemboursementParTirage" }  
    
repartitionParConcession:
    pattern:  /Répartition-Par-Concession.html
    defaults: { _controller: "EmpruntBundle:Remboursement:repartitionParConcession" }      
      
consulterRemboursementParConcession:
    pattern:  /Consulter-Remboursement-Par-Concession.html
    defaults: { _controller: "EmpruntBundle:Remboursement:consulterRemboursementParConcession" } 
    
afficherTableRemboursement:
    pattern:  /afficherTableRemboursement/{id}
    defaults: { _controller: "EmpruntBundle:Remboursement:afficherTableRemboursement" }    
    
displayTiragesList:
    pattern:  /displayTiragesList/{id}
    defaults: { _controller: "EmpruntBundle:Remboursement:displayTiragesList" }     
    
displayTirages:
    pattern:  /displayTirages/{id}
    defaults: { _controller: "EmpruntBundle:Remboursement:displayTirages" }        