tirage_display:
    pattern:  /display/{id}
    defaults: { _controller: "EmpruntBundle:Tirage:displayTirageForm" }

tirage:
    pattern:  /
    defaults: { _controller: "EmpruntBundle:Tirage:index" }

tirage_show:
    pattern:  /{id}/show
    defaults: { _controller: "EmpruntBundle:Tirage:show" }

tirage_new:
    pattern:  /new
    defaults: { _controller: "EmpruntBundle:Tirage:new" }

tirage_create:
    pattern:  /create
    defaults: { _controller: "EmpruntBundle:Tirage:create" }
    requirements: { _method: post }

tirage_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EmpruntBundle:Tirage:edit" }

tirage_update:
    pattern:  /{id}/update
    defaults: { _controller: "EmpruntBundle:Tirage:update" }
    requirements: { _method: post|put }

tirage_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EmpruntBundle:Tirage:delete" }
    requirements: { _method: post|delete }
