ConsulterUtilisateur:
    pattern:  /ConsulterUtilisateur
    defaults: { _controller: "EmpruntBundle:Utilisateur:consulterUtilisateur" }
    
AjouterUtilisateur:
    pattern:  /AjouterUtilisateur
    defaults: { _controller: "EmpruntBundle:Utilisateur:ajouterUtilisateur" }

display_utilisateur:
    pattern:  /display/{id}
    defaults: { _controller: "EmpruntBundle:Utilisateur:displayUtilisateurForm" }

ModifierUtilisateur:
    pattern:  /modifierUtilisateur/{id}
    defaults: { _controller: "EmpruntBundle:Utilisateur:modifierUtilisateur" }
    
SupprimerUtilisateur:
    pattern:  supprimerUtilisateur/{id}
    defaults: { _controller: "EmpruntBundle:Utilisateur:supprimerUtilisateur" }    
