parameters:
#    emprunt.example.class: ETAP\EmpruntBundle\Example

services:
#    emprunt.example:
#        class: %emprunt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
